# Generated by Django 4.0.1 on 2022-01-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=250, null=True)),
                ('token', models.CharField(max_length=250, null=True)),
                ('client_secret', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=400, null=True)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=400)),
                ('winner', models.CharField(max_length=400)),
                ('wins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=400)),
                ('date_asked', models.DateTimeField()),
                ('date_answered', models.DateTimeField(null=True)),
                ('winner', models.CharField(max_length=400, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='victorinaBot.question')),
            ],
        ),
    ]
